name: LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
            cd thesis
            pdflatex -interaction=nonstopmode -halt-on-error main.tex

      - name: Upload PDF
        uses: actions/upload-artifact@v4
        with:
          name: thesis-manak.pdf
          path: thesis/main.pdf
