name: LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build
        id: build
        run: |
            echo "date=`date +'%Y-%m-%d'`" >> "$GITHUB_OUTPUT"
            cd thesis
            pdflatex -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error main.tex
            bibtex main
            pdflatex -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error main.tex
            pdflatex -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error main.tex
            mkdir -p ../output
            mv main.pdf ../output/bcs-thesis.pdf

      - name: Upload
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: "output"
          remote_dir: "assets/content/documents"
