name: LaTeX

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Build
        id: build
        run: |
            echo "date=`date +'%Y-%m-%d'`" >> "$GITHUB_OUTPUT"
            cd thesis
            pdflatex -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error main.tex
            bibtex main
            pdflatex -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error main.tex
            pdflatex -shell-escape -synctex=1 -interaction=nonstopmode -file-line-error main.tex

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ steps.build.outputs.date }}
          files: thesis/main.pdf
          fail_on_unmatched_files: true
